# Page settings

baseURL = "http://example.org/"
languageCode = "en"
title = "Yes"
theme = "hugo-devresume-theme"
googleAnalytics = "UA-XXXXXXX-Y"


[mediaTypes]
  [mediaTypes.'application/pdf']
    suffixes = ['pdf']



[params]
    author = "CowboySmall"
    description = "DevResume - Bootstrap 4 Resume/CV Template For Software Developers"


    primaryColor = "#3858B6"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "Akos Poleczki"
        tagline = "Senior Software Engineer"
        avatar = "dark.png"







    [params.contact]
        enable = true
        location = "Oulu"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:#"
        text = "+36 30 51 84 898"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "akos.poleczki@gmail.com"







    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "Embedded Systems"
        [[params.skills.list.items]]
        details = "Telecommunication and networking (TCP/IP)"
        [[params.skills.list.items]]
        details = "Electrical Drives"
        [[params.skills.list.items]]
        details = "C and Modern C++"
        [[params.skills.list.items]]
        details = "Python, Java, Kotlin"
        [[params.skills.list.items]]
        details = "Linux"
        [[params.skills.list.items]]
        details = "Git, Gerrit, Jenkins"
        [[params.skills.list.items]]
        details = "Agile, Scrum, Kanban"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Highly motivated and active"
        [[params.skills.list.items]]
        details = "Effective communication"
        [[params.skills.list.items]]
        details = "Good team player"
        [[params.skills.list.items]]
        details = "Strong problem solver"
        [[params.skills.list.items]]
        details = "Fast learner"








    [params.education]
        enable = true

        [[params.education.list]]
        degree = "MSc in Electrical Engineering"
        university = "Budapest University of Technology and Economics"
        dates = "2019 - 2021"
        [[params.education.list]]
        degree = "BSc in Electrical Engineering"
        university = "Budapest University of Technology and Economics"
        dates = "2015 - 2019"








    [params.awards]
        enable = false

        [[params.awards.list]]
        name = "Award Lorem Ipsum"
        body = "Microsoft lorem ipsum"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"








    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "Hungarian"
        level = "Native"
        [[params.languages.list]]
        name = "English"
        level = "Fluent"
        [[params.languages.list]]
        name = "German"
        level = "Conversational"








    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Working on personal projects to solve real-world problems"
        [[params.interests.list]] 
        name = "Reading and self-improvement"
        [[params.interests.list]]
        name = "Learning languages"
        [[params.interests.list]]
        name = "Playing chess or other games"
        [[params.interests.list]]
        name = "Engaging in sports activities such as hiking, dancing, etc."








    [params.summary]
        enable = true
        text = "As a software developer with 5+ years of experience, I am a highly proactive individual who takes initiative and communicates effectively with my team members. My background includes extensive experience with embedded systems in the automotive industry as well as proficency in the telecommunication sector. In my most recent jobs, I had the opportunity to develop in C++, which quickly became my favorite programming language. Continuously striving to learn and refine my existing knowledge, I am enthusiastic about taking on new challenges and growing professionally."







    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Experienced Software Developer"
        dates = "2022 Jan - Present"
        company = "Nokia"
        details = "I contributed tAs a software developer with 5+ years of experience, I am a highly po diverse projects, including the dsadasd sd asd asd asd adas as."
        [[params.experience.list.items]]
        details = "Configurable DSCP values for GTP and PFCP messages on both the cloud native and legacy products"


        [[params.experience.list]]
        title = "Experienced Software Developer"
        dates = "2022 Jan - Present"
        company = "Ericsson"
        details = "I developed user-plane software for both legacy and cloud-native solutions in Ericsson's 5G core network. As a key member of the team, I played a vital role in feature planning, implementation, testing, and documentation to ensure project success. I also resolved both customer-reported and internally identified issues to maintain high standards of quality."
        [[params.experience.list.items]]
        details = "Configurable DSCP values for GTP and PFCP messages on both the cloud native and legacy products"
        [[params.experience.list.items]]
        details = "PFCP session related payload statistics counters for the cloud native product"
        [[params.experience.list.items]]
        details = "Investigated trouble reports for product configurability and performance issues"

        [[params.experience.list]]
        title = "Embedded Engineer"
        dates = "2018 Jun - 2022 Jan"
        company = "Thyssenkrupp - Rhiva - Hofer"
        details = "During my initial 2 years internship at Thyssenkrupp I was part of a team that underwent two company transfers. Following the first transfer, I was elevated to a full-time developer position. Throughout all of this journey, I had the responsibility of implementing, testing, and documenting diverse software components for an electric control unit and its test systems (HIL, PHIL). "
        [[params.experience.list.items]]
        details = "Design, implementation and testing of various hardware interfaces such as a digital encoder, an LCD screen, SPI, LVDS, PWM, etc."
        [[params.experience.list.items]]
        details = "Implementation of an openBLT-based dual microcontroller-fpga bootloader to enable flashing binaries through CAN bus"
        [[params.experience.list.items]]
        details = "Development the Java-based test-framework, writing regression and unit tests"

        [[params.experience.list]]
        title = "Programming Tutor"
        dates = "2018 Jan - 2018 Jun"
        company = "Logiscool"
        details = "Working as a student, I taught programming on different levels to children between the ages of 10-18."








    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "Text-based RPG game"
        meta = "Open Source"
        tagline = "This personal project was a crucial stepping stone in my journey to master modern C++ features effectively. Throughout the development process, I explored and implemented various optimizing viewpoints and software design patterns."

        [[params.projects.list]]
        title = "Whats for dinner"
        meta = "Open Source"
        tagline = "This Kotlin-based Android application offers a customizable and reliable way to track calorie and protein intake. It enables users to add new food items and set dietary goals, while also providing dinner ideas to help them achieve their objectives."

        [[params.projects.list]]
        title = "Cookeat"
        meta = "Open Source"
        tagline = "I developed this Kotlin-based Android application to offer cooking ideas to users based on their history of suggestions and a user-populated database."

        [[params.projects.list]]
        title = "Smart Alarm"
        meta = "Open Source"
        tagline = "I developed a smart alarm device using a ATmega328P microcontroller programmed in C. This project involved designing and soldering the hardware layout and implementing the necessary software interfaces. The device's goal is to provide a healthy way of waking up by gradually adjusting the brightness of a connected LED, imitating the sunrise, based on a pre-set wake-up time."

        #TODO: beleirni h itt ment uart stb esetlet a kotlinosokat meg egybe irni










    [params.information]
        enable = false

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "Climbing, Snowboarding, Photography, Travelling"








    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/Worrador"
        title = "Worrador"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//www.linkedin.com/in/%C3%A1kos-poleczki-1b7978151/"
        title = "Ákos Poleczki"




[params.footer]
    copyright = ""
